# Generated by Django 4.0.6 on 2022-08-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_publish_date',
            new_name='post_publication_date',
        ),
    ]
